plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: aqua
locale: zh-CN
title: 三番木四
name: 潘杰
description: 潘杰的个人网站，包含但不限于技术文章、学习笔记等。
baseurl: ""
url: https://www.jackpan.me
repository: "jack0pan/jack0pan"
words_per_minute: 200
comments:
  provider: giscus
  giscus:
    repo_id: jack0pan/jack0pan
    category_name: General
    category_id: DIC_kwDOEqheDc4CBCjL
    theme: preferred_color_scheme

search: true
search_provider: algolia
algolia:
  application_id: QOYY610WDW
  index_name: prod
  search_only_api_key: 5ffcd47fe54ef2621193bd1e02c9d54b

twitter:
  username: jack0pan
facebook:
  username: jack.pan.965

author: Jack

footer:
  links:
    - label: Website
      icon: "fas fa-fw fa-link"
      url: https://www.jackpan.me
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: https://github.com/jack0pan

pageinate: 10

timezone: Asia/Shanghai

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

collections:
  docs:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
